<%
  env = YAML.load(IO.read('/home/dotcloud/environment.yml')) if Rails.env.production?
%>
production:
  sessions:
    default:
      database: <%= env['DOTCLOUD_PROJECT'] + '_production' %>
      hosts:
        - <%= env['DOTCLOUD_DB_MONGODB_HOST'] + ':' + env['DOTCLOUD_DB_MONGODB_PORT'] %>
      password: <%= env['DOTCLOUD_DB_MONGODB_PASSWORD'] %>
      username: <%= env['DOTCLOUD_DB_MONGODB_LOGIN'] %>  
      options: 
        safe: false
        consistency: :eventual
        max_retries: 30
        retry_interval: 1
  options:
development:
  sessions:
    default:
      database: stripemetrics_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: stripemetrics_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
