<%
  if File.exist?('/home/deploy/environment.yml')
    mongo = YAML.load(IO.read('/home/deploy/environment.yml'))
  else
    mongo = { 
              'STRIPEMETRICS_PROJECT'=>'stripemetrics',
              'STRIPEMETRICS_MONGODB_HOST'=> 'localhost',
              'STRIPEMETRICS_MONGODB_PORT' => '27017'
            }
  end  
%>
production:
  sessions:
    default:
      database: <%= mongo['STRIPEMETRICS_PROJECT'] + '_production' %>
      hosts:
        - <%= mongo['STRIPEMETRICS_MONGODB_HOST'] + ':' + mongo['STRIPEMETRICS_MONGODB_PORT'] %>
      options: 
        safe: false
        consistency: :eventual
        max_retries: 30
        retry_interval: 1
  options:

development:
  sessions:
    default:
      database: stripemetrics_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  sessions:
    default:
      database: stripemetrics_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
