---

- hosts: www
  user: deploy
  sudo: false
  connection: ssh

  vars:
    app_name: stripemetrics
    repo_url: git@github.com:yacc/stripemetrics.git
    repo_remote: origin
    repo_branch: master
    webapps_dir: /home/deploy/www

  tasks:
    - name: deploy code from repository
      action: git repo=$repo_url dest=${webapps_dir}/${app_name} remote=$repo_remote version=$repo_branch

    - name: bundle install
      shell: bundle install v

    - name: compile assets
      shell: RAILS_ENV=production bundle exec rake assets:precompile chdir=${webapps_dir}/${app_name}/base 
      notify:
        - restart app

  handlers:
    - name: restart app
      shell: touch tmp/restart.txt chdir=${webapps_dir}/${app_name}/base
  

  # ANSIBLE_SSH_ARGS="" ansible-playbook playbooks/deploy.yml -i ansible_hosts
  # edit /etc/sudoers with visudo
  # after this line
  #Defaults    env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"
  #add
  #+Defaults    env_keep += "SSH_AUTH_SOCK"