source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'mongoid', '>3'
gem "bson_ext"
gem "thin"

gem "grape"
gem "warden"
gem "cancan", ">= 1.6.8"
gem "bcrypt-ruby", :require => "bcrypt"

group :development do
  gem 'rake'
  gem 'rspec'
end

group :test do
  gem 'rack-test'
  gem 'rake'
  gem 'rspec'
end
