source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'mongoid', '>3'
gem "bson_ext" #, :platforms => :mri
gem "thin"

gem "cancan", ">= 1.6.8"
gem "grape"

group :development do
  gem 'rake'
  gem 'rspec'
end

group :test do
  gem 'rack-test'
  gem 'rake'
  gem 'rspec'
end
